AWSTemplateFormatVersion: '2010-09-09'

Description: Blockchain DevOps Infrastructure

Resources:
  LogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: blockchain-devops-log-group
      RetentionInDays: 7